version: "3.5"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.0"
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
            - "discovery.type=single-node"
            - xpack.security.enabled=true
            - xpack.security.audit.enabled=true
            - ELASTIC_USERNAME=ansc
            - ELASTIC_PASSWORD=ansc
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data

    kibana:
        image: "docker.elastic.co/kibana/kibana:7.15.0"
        ports:
            - "5601:5601"
        environment:
            - xpack.security.enabled=true
            - ELASTICSEARCH_USERNAME=ansc
            - ELASTICSEARCH_PASSWORD=ansc

    filebeat:
        image: "docker.elastic.co/beats/filebeat:7.15.0"
        user: root
        volumes:
            - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
            - /var/lib/docker:/var/lib/docker:ro
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    elasticsearch_data: