filebeat.inputs:
- type: container
  paths: 
    - '/var/lib/docker/containers/*/*.log'

processors:
  - add_docker_metadata:
    host: "unix:///var/run/docker.sock"
  - decode_xml:
      field: message
      target_field: xml
      to_lower: false
      ignore_missing: true
      ignore_failure: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-elastic-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.image.name: docker.elastic.co/beats/filebeat:7.15.0
        - equals:
            container.image.name: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
        - equals:
            container.image.name: docker.elastic.co/kibana/kibana:7.15.0
    - index: "filebeat-scriptal-%{+yyyy.MM.dd}"
      when.or:
        - equals:
            container.image.name: scriptal/nexsis:0.1.0
        - contains:
            container.image.name: scriptal
        - contains:
            container.container.name: scriptal

    - index: "filebeat-failed-%{+yyyy.MM.dd}"